controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Homepage:
    path: /home
    controller: "App/Controller/HomeController::index"

Recipes:
    path: /recipes
    controller: "App/Controller/RecipesController::index"

About:
    path: /about
    controller: "App/Controller/AboutController::index"

Services:
    path: /services
    controller: "App/Controller/ServicesController::index"

Contact:
    path: /contact
    controller: "App/Controller/ContactController::index"
