controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Homepage:
    path: /
    controller: "App/Controller/HomeController::index"

Recipes:
    path: /recipes
    controller: "App/Controller/RecipesController::index"

About:
    path: /about
    controller: "App/Controller/AboutController::index"

Services:
    path: /services
    controller: "App/Controller/ServicesController::index"

Contact:
    path: /contact
    controller: "App/Controller/ContactController::index"

app_login:
    path: /login
    controller: "App:Controller/SecurityController::index"

admin:
    path: /admin
    controller: "App:Controller/AdminController::index"

admin_add:
    path: /admin/add
    controller: "App:Controller/AdminController::add"

admin_remove:
    path: /admin/_remove/{id}
    controller: "App/Controller/AdminController::remove"
    requirements:
        id: '\d+'


admin_edit:
    path: /admin/_edit/{id}
    controller: "App/Controller/AdminController::edit"
    requirements:
        id: '\d+'

admin_recipe:
    path: /admin/_recipe
    controller: "App:Controller/AdminController::index_recipe"


admin_add_recipe:
    path: /admin/add_recipe
    controller: "App:Controller/AdminController::add_recipe"


admin_edit_recipe:
    path: /admin/_edit_recipe/{id}
    controller: "App/Controller/AdminController::edit_recipe"
    requirements:
        id: '\d+'

admin_remove_recipe:
    path: /admin/_remove_recipe/{id}
    controller: "App/Controller/AdminController::remove_recipe"
    requirements:
        id: '\d+'

_recipe:
    path: /recipes/_recipe/{id}
    controller: "App/Controller/RecipesController::show"
    requirements:
        id: '\d+'
